// <auto-generated />
using System;
using HackerRank1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HackerRank1.Migrations
{
    [DbContext(typeof(SigacDbContext))]
    partial class SigacDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HackerRank1.Entities.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("clave");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.ToTable("permiso", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Clave = "donaciones.crear",
                            Descripcion = "Crear donaciones"
                        },
                        new
                        {
                            Id = 2,
                            Clave = "donaciones.ver",
                            Descripcion = "Ver donaciones"
                        },
                        new
                        {
                            Id = 3,
                            Clave = "donaciones.editar",
                            Descripcion = "Editar donaciones"
                        },
                        new
                        {
                            Id = 4,
                            Clave = "donaciones.eliminar",
                            Descripcion = "Eliminar donaciones"
                        },
                        new
                        {
                            Id = 5,
                            Clave = "beneficiarios.gestionar",
                            Descripcion = "Gestionar beneficiarios"
                        },
                        new
                        {
                            Id = 6,
                            Clave = "inventario.gestionar",
                            Descripcion = "Gestionar inventario"
                        },
                        new
                        {
                            Id = 7,
                            Clave = "gastos.gestionar",
                            Descripcion = "Gestionar gastos"
                        },
                        new
                        {
                            Id = 8,
                            Clave = "usuarios.ver",
                            Descripcion = "Ver usuarios"
                        },
                        new
                        {
                            Id = 9,
                            Clave = "usuarios.gestionar",
                            Descripcion = "Gestionar usuarios"
                        },
                        new
                        {
                            Id = 10,
                            Clave = "usuarios.crear_admin",
                            Descripcion = "Crear administradores"
                        },
                        new
                        {
                            Id = 11,
                            Clave = "roles.ver",
                            Descripcion = "Ver roles"
                        },
                        new
                        {
                            Id = 12,
                            Clave = "roles.gestionar",
                            Descripcion = "Gestionar roles"
                        },
                        new
                        {
                            Id = 13,
                            Clave = "roles.asignar",
                            Descripcion = "Asignar roles a usuarios"
                        });
                });

            modelBuilder.Entity("HackerRank1.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("rol", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Rol básico de usuario",
                            Nombre = "usuario"
                        },
                        new
                        {
                            Id = 2,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Rol de administrador operativo",
                            Nombre = "administrador"
                        },
                        new
                        {
                            Id = 3,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Rol de superusuario con todos los permisos",
                            Nombre = "superusuario"
                        });
                });

            modelBuilder.Entity("HackerRank1.Entities.RolPermiso", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    b.Property<int>("PermisoId")
                        .HasColumnType("integer")
                        .HasColumnName("permiso_id");

                    b.HasKey("RolId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("rol_permiso", (string)null);

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            PermisoId = 1
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 2
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 1
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 2
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 3
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 4
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 5
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 6
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 7
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 8
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 9
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 11
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 1
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 2
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 3
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 4
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 5
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 6
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 7
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 8
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 9
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 10
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 11
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 12
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 13
                        });
                });

            modelBuilder.Entity("HackerRank1.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("HackerRank1.Entities.RolPermiso", b =>
                {
                    b.HasOne("HackerRank1.Entities.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HackerRank1.Entities.Rol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("HackerRank1.Entities.Usuario", b =>
                {
                    b.HasOne("HackerRank1.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("HackerRank1.Entities.Permiso", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("HackerRank1.Entities.Rol", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
